#include <string>
#include <unordered_map>

using namespace std;

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.


Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/


char findTheDifference(string s, string t)
{
    unordered_map<char, int> sLetters = unordered_map<char, int>();
    unordered_map<char, int> tLetters = unordered_map<char, int>();

    for (char c : s)
    {
        sLetters[c]++;
    }

    for (char c : t)
    {
        tLetters[c]++;
    }

    for (const auto& p : tLetters)
    {
        if (!sLetters.count(p.first) || (sLetters.count(p.first) && p.second > sLetters[p.first]))
        {
            return p.first;
        }
    }

    return ' ';
}


int main()
{
    string s = "a";
    string t = "aa";

    char result = findTheDifference(s, t);

    return 0;
}